# Generated by Django 6.0.6 on 2026-07-05 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('ward_numbers', models.JSONField(default=list, help_text='e.g. [1, 2, 3]')),
                ('base_delivery_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estimated_delivery_time_minutes', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('unassigned', 'Unassigned'), ('assigned', 'Assigned'), ('picked_up', 'Picked up'), ('delivered', 'Delivered'), ('failed', 'Failed')], default='unassigned', max_length=12)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_fee_owed_to_rider', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('failure_reason', models.TextField(blank=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='delivery', to='orders.order')),
                ('rider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to='accounts.riderprofile')),
            ],
            options={
                'verbose_name_plural': 'deliveries',
                'indexes': [models.Index(fields=['status'], name='delivery_de_status_6efeaa_idx'), models.Index(fields=['rider', 'status'], name='delivery_de_rider_i_6efa7d_idx')],
            },
        ),
    ]
