# Generated by Django 6.0.6 on 2026-07-05 20:33

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiderProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('bike', 'Bike'), ('bicycle', 'Bicycle'), ('on_foot', 'On foot')], max_length=10)),
                ('is_available', models.BooleanField(default=False)),
                ('total_deliveries', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SellerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication_rating', models.PositiveSmallIntegerField(default=5, help_text='1-5: seller communication responsiveness')),
                ('shipping_speed_rating', models.PositiveSmallIntegerField(default=5, help_text='1-5: delivery speed vs promise')),
                ('product_accuracy_rating', models.PositiveSmallIntegerField(default=5, help_text='1-5: product matched description')),
                ('overall_rating', models.PositiveSmallIntegerField(help_text='1-5 overall seller rating')),
                ('title', models.CharField(blank=True, max_length=120)),
                ('comment', models.TextField(blank=True)),
                ('would_recommend', models.BooleanField(default=True)),
                ('is_verified_purchase', models.BooleanField(default=True)),
                ('vendor_response', models.TextField(blank=True)),
                ('vendor_responded_at', models.DateTimeField(blank=True, null=True)),
                ('helpful_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=120)),
                ('shop_slug', models.SlugField(max_length=140, unique=True)),
                ('shop_description', models.TextField(blank=True)),
                ('shop_logo', models.ImageField(blank=True, upload_to='shop_logos/')),
                ('shop_municipality', models.CharField(choices=[('Hetauda', 'hetauda'), ('Bagmati', 'bagmati'), ('Bakaiya', 'bakaiya'), ('Thaha', 'thaha'), ('Makwanpur Gadhi', 'makwanpur gadhi'), ('Manahari', 'manahari'), ('Bhimphedi', 'bhimphedi'), ('Indrasarobar', 'indrasarobar')], default='Hetauda', help_text='Shop physical municipality for location-based search.', max_length=100)),
                ('shop_ward_number', models.PositiveSmallIntegerField(default=4, help_text='Hetauda ward number for hyperlocal discovery.')),
                ('shop_landmark', models.CharField(blank=True, help_text='Nearby landmark for pickup/returns.', max_length=200)),
                ('shop_full_address', models.TextField(blank=True, help_text='Full shop address for customers.')),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', help_text="Set to 'verified' after manual vetting.", max_length=10)),
                ('verified_at', models.DateTimeField(blank=True, help_text='Timestamp when verification was granted.', null=True)),
                ('verification_notes', models.TextField(blank=True, help_text='Internal notes from verification team.')),
                ('commission_rate', models.DecimalField(decimal_places=2, default=5.0, help_text='Per-vendor rate (%). Snapshotted onto OrderItem at order time.', max_digits=5)),
                ('agreement_signed_at', models.DateTimeField(blank=True, null=True)),
                ('listing_fee_exempt_until', models.DateField(blank=True, help_text='Implements the "free first year" policy.', null=True)),
                ('payout_method', models.CharField(choices=[('esewa', 'eSewa'), ('khalti', 'Khalti'), ('bank', 'Bank transfer')], max_length=10)),
                ('payout_account_details', models.TextField(help_text='ENCRYPT AT REST in production.')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('total_sales', models.PositiveIntegerField(default=0)),
                ('total_reviews_count', models.PositiveIntegerField(default=0, help_text='Denormalized seller review count.')),
                ('trust_score', models.PositiveSmallIntegerField(default=0, help_text='0-100 composite trust score: verification + rating + sales + response time.')),
                ('is_trusted_seller', models.BooleanField(default=False, help_text='Auto-calculated: verified + rating>=4.2 + sales>=50')),
                ('return_window_days', models.PositiveSmallIntegerField(default=3, help_text='Return window in days, displayed on every product page.')),
                ('return_policy_text', models.TextField(default='3-Day Doorstep Replacement: If the size does not fit or the fabric has any manufacturing defect, notify us within 3 days. Our local rider will pick up the item and deliver your replacement at your doorstep, or you can exchange directly at our physical stall.', help_text='Vendor-specific return policy — shown transparently on every product page.')),
                ('accepts_returns', models.BooleanField(default=True)),
                ('refund_method', models.CharField(choices=[('replacement', 'Replacement'), ('refund', 'Full Refund'), ('store_credit', 'Store Credit'), ('both', 'Refund or Replacement')], default='both', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(help_text='Used for SMS notifications and OTP.', max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^\\+?977?9\\d{9}$', 'Enter a valid Nepali mobile number.')])),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('vendor', 'Vendor'), ('rider', 'Rider'), ('admin', 'Admin')], default='customer', max_length=10)),
                ('is_phone_verified', models.BooleanField(default=False)),
                ('profile_picture', models.ImageField(blank=True, upload_to='profiles/')),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('ne', 'नेपाली')], default='en', max_length=2)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text='e.g. "Home", "Shop"', max_length=50)),
                ('full_address', models.TextField()),
                ('landmark', models.TextField(blank=True, help_text='Nearby landmark — often more useful than street address.')),
                ('municipality', models.CharField(choices=[('Hetauda', 'hetauda'), ('Bagmati', 'bagmati'), ('Bakaiya', 'bakaiya'), ('Thaha', 'thaha'), ('Makwanpur Gadhi', 'makwanpur gadhi'), ('Manahari', 'manahari'), ('Bhimphedi', 'bhimphedi'), ('Indrasarobar', 'indrasarobar')], max_length=100)),
                ('ward_number', models.PositiveSmallIntegerField()),
                ('is_default', models.BooleanField(default=False)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'addresses',
            },
        ),
    ]
