# Generated by Django 6.0.6 on 2026-07-05 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0002_initial'),
        ('delivery', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderprofile',
            name='current_zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='riders', to='delivery.deliveryzone'),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rider_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sellerreview',
            name='order',
            field=models.ForeignKey(blank=True, help_text='Verified purchase link — prevents fake seller reviews.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_reviews', to='orders.order'),
        ),
        migrations.AddField(
            model_name='sellerreview',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_seller_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='category',
            field=models.ForeignKey(help_text='Primary category the vendor sells in.', on_delete=django.db.models.deletion.PROTECT, related_name='vendors', to='catalog.category'),
        ),
        migrations.AddField(
            model_name='vendorprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sellerreview',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_reviews', to='accounts.vendorprofile'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'is_active'], name='accounts_us_role_2b136f_idx'),
        ),
        migrations.AddConstraint(
            model_name='address',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('user',), name='one_default_address_per_user'),
        ),
        migrations.AddIndex(
            model_name='riderprofile',
            index=models.Index(fields=['is_available'], name='accounts_ri_is_avai_c3e922_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorprofile',
            index=models.Index(fields=['verification_status'], name='accounts_ve_verific_6b9f5b_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorprofile',
            index=models.Index(fields=['shop_municipality', 'shop_ward_number'], name='accounts_ve_shop_mu_863f4c_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorprofile',
            index=models.Index(fields=['average_rating', '-total_sales'], name='accounts_ve_average_098617_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorprofile',
            index=models.Index(fields=['is_trusted_seller'], name='accounts_ve_is_trus_10a00d_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerreview',
            index=models.Index(fields=['vendor', '-created_at'], name='accounts_se_vendor__58579d_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerreview',
            index=models.Index(fields=['overall_rating'], name='accounts_se_overall_be8f91_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerreview',
            index=models.Index(fields=['is_verified_purchase'], name='accounts_se_is_veri_8642bd_idx'),
        ),
        migrations.AddConstraint(
            model_name='sellerreview',
            constraint=models.UniqueConstraint(condition=models.Q(('order__isnull', False)), fields=('vendor', 'reviewer', 'order'), name='unique_seller_review_per_order'),
        ),
    ]
