# Generated by Django 6.0.6 on 2026-07-06 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderprofile',
            name='average_delivery_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='ban_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='citizenship_back_image',
            field=models.ImageField(blank=True, upload_to='rider_kyc/citizenship/'),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='citizenship_front_image',
            field=models.ImageField(blank=True, help_text='Citizenship front — encrypted at rest in production', upload_to='rider_kyc/citizenship/'),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='citizenship_number',
            field=models.CharField(blank=True, help_text='Nepal Citizenship No. — e.g. 27-01-76-12345', max_length=30),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='current_municipality',
            field=models.CharField(choices=[('Hetauda', 'hetauda'), ('Bagmati', 'bagmati'), ('Bakaiya', 'bakaiya'), ('Thaha', 'thaha'), ('Makwanpur Gadhi', 'makwanpur gadhi'), ('Manahari', 'manahari'), ('Bhimphedi', 'bhimphedi'), ('Indrasarobar', 'indrasarobar')], default='Hetauda', max_length=100),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='current_ward',
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='kyc_rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='kyc_status',
            field=models.CharField(choices=[('not_submitted', 'KYC Not Submitted'), ('pending', 'Pending Verification'), ('in_review', 'In Review'), ('verified', 'KYC Verified'), ('rejected', 'KYC Rejected'), ('suspended', 'Suspended')], db_index=True, default='not_submitted', help_text='Rider must be KYC VERIFIED before accepting delivery tasks.', max_length=15),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='kyc_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='kyc_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='kyc_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_riders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='license_image',
            field=models.ImageField(blank=True, upload_to='rider_kyc/license/'),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='license_number',
            field=models.CharField(blank=True, help_text='Driving license No. — required for BIKE vehicle_type', max_length=30),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='permanent_address',
            field=models.TextField(blank=True, help_text='Permanent address as per citizenship'),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='selfie_with_id',
            field=models.ImageField(blank=True, help_text='Liveness check — selfie holding citizenship', upload_to='rider_kyc/selfie/'),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='total_ratings',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='vehicle_bluebook_image',
            field=models.ImageField(blank=True, help_text='Vehicle registration (bluebook)', upload_to='rider_kyc/bluebook/'),
        ),
        migrations.AddField(
            model_name='riderprofile',
            name='vehicle_registration_number',
            field=models.CharField(blank=True, help_text='e.g. Ba 19 Pa 1234 — Nepal number plate', max_length=20),
        ),
        migrations.AddIndex(
            model_name='riderprofile',
            index=models.Index(fields=['kyc_status', 'is_available'], name='accounts_ri_kyc_sta_0be106_idx'),
        ),
        migrations.AddIndex(
            model_name='riderprofile',
            index=models.Index(fields=['current_zone', 'is_available'], name='accounts_ri_current_a98f24_idx'),
        ),
    ]
